% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={WHI.TotalPA.an\_samp},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{WHI.TotalPA.an\_samp}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Autogenerated data summary from dataMaid}
\author{}
\date{\vspace{-2.5em}2023-11-14 14:54:55}

\begin{document}
\maketitle

\hypertarget{data-report-overview}{%
\section{Data report overview}\label{data-report-overview}}

The dataset examined has the following dimensions:

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3472}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1250}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Number of observations & 83410 \\
Number of variables & 75 \\
\end{longtable}

\hypertarget{checks-performed}{%
\subsubsection{Checks performed}\label{checks-performed}}

The following variable checks were performed, depending on the data type
of each variable:

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.3750}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0833}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0694}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0764}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.1181}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0694}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0694}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0694}}
  >{\centering\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.0694}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
~
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
character
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
factor
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
labelled
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
haven labelled
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
numeric
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
integer
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
logical
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Date
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Identify miscoded missing values & × & × & × & × & × & × & & × \\
Identify prefixed and suffixed whitespace & × & × & × & × & & & & \\
Identify levels with \textless{} 6 obs. & × & × & × & × & & & & \\
Identify case issues & × & × & × & × & & & & \\
Identify misclassified numeric or integer variables & × & × & × & × & &
& & \\
Identify outliers & & & & & × & × & & × \\
\end{longtable}

Please note that all numerical values in the following have been rounded
to 2 decimals.

\hypertarget{summary-table}{%
\section{Summary table}\label{summary-table}}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1778}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1889}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.2000}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.2556}}
  >{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1778}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
~
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Variable class
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
\# unique values
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Missing observations
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Any problems?
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\protect\hyperlink{id}{ID} & numeric & 83410 & 0.00 \% & \\
\protect\hyperlink{osflag}{OSFLAG} & numeric & 2 & 0.00 \% & \\
\protect\hyperlink{age}{AGE} & numeric & 33 & 0.00 \% & \\
\protect\hyperlink{ethnic}{ETHNIC} & numeric & 7 & 0.22 \% & × \\
\protect\hyperlink{hrtarm}{HRTARM} & numeric & 5 & 0.00 \% & \\
\protect\hyperlink{dmarm}{DMARM} & numeric & 3 & 0.00 \% & \\
\protect\hyperlink{mi_f2}{mi\_f2} & numeric & 2 & 0.03 \% & × \\
\protect\hyperlink{diabtrt}{DIABTRT} & numeric & 3 & 0.06 \% & \\
\protect\hyperlink{nomam2yr}{NOMAM2YR} & numeric & 3 & 2.84 \% & \\
\protect\hyperlink{timelsts}{TIMELSTS} & hms & 3 & 3.31 \% & × \\
\protect\hyperlink{anyins}{ANYINS} & numeric & 3 & 0.86 \% & \\
\protect\hyperlink{nses}{nses} & numeric & 36356 & 10.53 \% & × \\
\protect\hyperlink{hicholrp}{HICHOLRP} & numeric & 3 & 1.50 \% & \\
\protect\hyperlink{hei2005}{HEI2005} & numeric & 82311 & 0.16 \% & × \\
\protect\hyperlink{f60sodum}{F60SODUM} & numeric & 83263 & 0.16 \% &
× \\
\protect\hyperlink{pulse30}{PULSE30} & numeric & 75 & 0.17 \% & × \\
\protect\hyperlink{waist}{WAIST} & numeric & 788 & 0.36 \% & × \\
\protect\hyperlink{syst}{SYST} & numeric & 115 & 0.09 \% & \\
\protect\hyperlink{dias}{DIAS} & numeric & 91 & 0.11 \% & × \\
\protect\hyperlink{bmi}{BMI} & numeric & 50373 & 0.87 \% & × \\
\protect\hyperlink{walk}{WALK} & numeric & 6 & 0.00 \% & \\
\protect\hyperlink{walkmin}{WALKMIN} & numeric & 5 & 14.01 \% & \\
\protect\hyperlink{walkspd}{WALKSPD} & numeric & 6 & 14.00 \% & × \\
\protect\hyperlink{hrdex}{HRDEX} & numeric & 7 & 0.82 \% & \\
\protect\hyperlink{hrdexmin}{HRDEXMIN} & numeric & 5 & 72.23 \% & \\
\protect\hyperlink{modex}{MODEX} & numeric & 7 & 0.82 \% & \\
\protect\hyperlink{modexmin}{MODEXMIN} & numeric & 5 & 52.76 \% & \\
\protect\hyperlink{mldex}{MLDEX} & numeric & 7 & 1.69 \% & \\
\protect\hyperlink{mldexmin}{MLDEXMIN} & numeric & 5 & 72.50 \% & \\
\protect\hyperlink{hrdex18}{HRDEX18} & numeric & 3 & 3.07 \% & \\
\protect\hyperlink{hrdex35}{HRDEX35} & numeric & 3 & 2.72 \% & \\
\protect\hyperlink{hrdex50}{HRDEX50} & numeric & 3 & 2.05 \% & \\
\protect\hyperlink{tepiwk}{TEPIWK} & numeric & 43 & 0.00 \% & × \\
\protect\hyperlink{lepitot}{LEPITOT} & numeric & 43 & 0.00 \% & × \\
\protect\hyperlink{msepiwk}{MSEPIWK} & numeric & 31 & 0.00 \% & \\
\protect\hyperlink{xlmsepi}{XLMSEPI} & numeric & 31 & 0.00 \% & \\
\protect\hyperlink{lmsepi}{LMSEPI} & numeric & 4 & 0.00 \% & \\
\protect\hyperlink{sepiwk}{SEPIWK} & numeric & 6 & 0.00 \% & \\
\protect\hyperlink{tminwk}{TMINWK} & numeric & 330 & 0.00 \% & × \\
\protect\hyperlink{msminwk}{MSMINWK} & numeric & 235 & 0.00 \% & × \\
\protect\hyperlink{sminwk}{SMINWK} & numeric & 19 & 0.00 \% & \\
\protect\hyperlink{texpwk}{TEXPWK} & numeric & 1341 & 0.00 \% & × \\
\protect\hyperlink{walkexp}{WALKEXP} & numeric & 41 & 0.00 \% & × \\
\protect\hyperlink{smoking}{SMOKING} & numeric & 4 & 0.93 \% & \\
\protect\hyperlink{hardexp}{HARDEXP} & numeric & 19 & 0.00 \% & \\
\protect\hyperlink{modexp}{MODEXP} & numeric & 19 & 0.00 \% & \\
\protect\hyperlink{mildexp}{MILDEXP} & numeric & 19 & 0.00 \% & \\
\protect\hyperlink{alcohol}{ALCOHOL} & numeric & 7 & 0.47 \% & \\
\protect\hyperlink{packyrs}{PACKYRS} & numeric & 203 & 3.18 \% & \\
\protect\hyperlink{indrchor}{INDRCHOR} & numeric & 6 & 39.68 \% & \\
\protect\hyperlink{yrdworkm}{YRDWORKM} & numeric & 6 & 39.83 \% & \\
\protect\hyperlink{yrdwrkh}{YRDWRKH} & numeric & 6 & 63.15 \% & \\
\protect\hyperlink{sitting}{SITTING} & numeric & 9 & 39.79 \% & \\
\protect\hyperlink{sleeping}{SLEEPING} & numeric & 9 & 39.69 \% & × \\
\protect\hyperlink{yrdminwk}{YRDMINWK} & numeric & 15 & 40.00 \% & \\
\protect\hyperlink{yardexp}{YARDEXP} & numeric & 15 & 40.00 \% & \\
\protect\hyperlink{inheaexp}{INHEAEXP} & numeric & 6 & 39.68 \% & \\
\protect\hyperlink{inact}{INACT} & numeric & 18 & 39.88 \% & × \\
\protect\hyperlink{totestat}{TOTESTAT} & numeric & 4 & 0.06 \% & \\
\protect\hyperlink{totpstat}{TOTPSTAT} & numeric & 4 & 0.04 \% & \\
\protect\hyperlink{tothstat}{TOTHSTAT} & numeric & 4 & 0.09 \% & \\
\protect\hyperlink{nightswt}{NIGHTSWT} & numeric & 5 & 0.48 \% & \\
\protect\hyperlink{hotflash}{HOTFLASH} & numeric & 5 & 0.31 \% & \\
\protect\hyperlink{actdly}{ACTDLY} & numeric & 9 & 3.25 \% & × \\
\protect\hyperlink{physfun}{PHYSFUN} & numeric & 20 & 0.80 \% & × \\
\protect\hyperlink{pshtdep}{PSHTDEP} & numeric & 2652 & 1.89 \% & × \\
\protect\hyperlink{socfunc}{SOCFUNC} & numeric & 10 & 0.28 \% & \\
\protect\hyperlink{htnrx}{HTNrx} & numeric & 3 & 0.00 \% & \\
\protect\hyperlink{f33pillshyp}{F33PILLSHYP} & numeric & 2 & 0.00 \%
& \\
\protect\hyperlink{timedy}{timedy} & numeric & 6547 & 0.00 \% & \\
\protect\hyperlink{timeyr}{timeyr} & numeric & 6547 & 0.00 \% & \\
\protect\hyperlink{educcat}{educcat} & numeric & 4 & 0.74 \% & \\
\protect\hyperlink{hxchd}{HxCHD} & numeric & 1 & 0.00 \% & × \\
\protect\hyperlink{prevcanc}{prevCanc} & numeric & 2 & 0.00 \% & \\
\protect\hyperlink{stroke_f2}{stroke\_f2} & numeric & 1 & 0.00 \% & × \\
\end{longtable}

\hypertarget{variable-list}{%
\section{Variable list}\label{variable-list}}

\hypertarget{id}{%
\subsection{ID}\label{id}}

\emph{WHI Participant Common ID}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3056}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 83410 \\
Median & 200093.5 \\
1st and 3rd quartiles & 150549.5; 249564.75 \\
Min. and max. & 100001; 299999 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-1-ID-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{osflag}{%
\subsection{OSFLAG}\label{osflag}}

\emph{OS Participant}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1389}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 2 \\
Mode & ``1'' \\
Reference category & 0 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-2-OSFLAG-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{age}{%
\subsection{AGE}\label{age}}

\emph{Age at screening}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1389}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 33 \\
Median & 61 \\
1st and 3rd quartiles & 56; 67 \\
Min. and max. & 49; 81 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-3-AGE-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{ethnic}{%
\subsection{ETHNIC}\label{ethnic}}

\emph{Ethnicity}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2083}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 186 (0.22 \%) \\
Number of unique values & 6 \\
Median & 5 \\
1st and 3rd quartiles & 5; 5 \\
Min. and max. & 1; 8 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-4-ETHNIC-1.pdf}

\begin{itemize}
\item
  The following suspected missing value codes enter as regular values:
  "8".
\item
  Note that the following possible outlier values were detected: "1",
  "2", "3", "4", "8".
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{hrtarm}{%
\subsection{HRTARM}\label{hrtarm}}

\emph{HRT Arm}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1389}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 5 \\
Mode & ``0'' \\
Reference category & 0 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-5-HRTARM-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{dmarm}{%
\subsection{DMARM}\label{dmarm}}

\emph{DM Arm}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1389}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 3 \\
Mode & ``0'' \\
Reference category & 0 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-6-DMARM-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{mi_f2}{%
\subsection{mi\_f2}\label{mi_f2}}

\emph{MI ever}

\begin{itemize}
\tightlist
\item
  The variable only takes one (non-missing) value: "0". The variable
  contains 0.03 \% missing observations.
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{diabtrt}{%
\subsection{DIABTRT}\label{diabtrt}}

\emph{Diabetes treated (pills or shots)}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1944}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 51 (0.06 \%) \\
Number of unique values & 2 \\
Mode & ``0'' \\
Reference category & 0 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-8-DIABTRT-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{nomam2yr}{%
\subsection{NOMAM2YR}\label{nomam2yr}}

\emph{No mammogram in last 2 years}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2222}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 2365 (2.84 \%) \\
Number of unique values & 2 \\
Mode & ``0'' \\
Reference category & 0 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-9-NOMAM2YR-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{timelsts}{%
\subsection{TIMELSTS}\label{timelsts}}

\begin{itemize}
\tightlist
\item
  The variable has class hms which is not supported by dataMaid.
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{anyins}{%
\subsection{ANYINS}\label{anyins}}

\emph{Any Insurance}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2083}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 718 (0.86 \%) \\
Number of unique values & 2 \\
Mode & ``1'' \\
Reference category & 0 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-11-ANYINS-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{nses}{%
\subsection{nses}\label{nses}}

\emph{Neighborhood SES}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2361}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 8785 (10.53 \%) \\
Number of unique values & 36355 \\
Median & 77.95 \\
1st and 3rd quartiles & 72.99; 81.9 \\
Min. and max. & 27.83; 98.37 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-12-nses-1.pdf}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected:
  "27.83", "27.92", "28.01", "28.47", "28.56", \ldots, "97.87", "98.07",
  "98.18", "98.22", "98.37" (1419 values omitted).
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{hicholrp}{%
\subsection{HICHOLRP}\label{hicholrp}}

\emph{High cholesterol requiring pills ever}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2083}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 1250 (1.5 \%) \\
Number of unique values & 2 \\
Mode & ``0'' \\
Reference category & 0 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-13-HICHOLRP-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{hei2005}{%
\subsection{HEI2005}\label{hei2005}}

\emph{TOTAL HEI-2005 SCORE}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2083}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 136 (0.16 \%) \\
Number of unique values & 82310 \\
Median & 69.32 \\
1st and 3rd quartiles & 60.8; 76.08 \\
Min. and max. & 22.72; 93.44 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-14-HEI2005-1.pdf}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected:
  "22.72", "23.65", "24.75", "25.79", "25.86", \ldots, "92.23", "92.44",
  "93.02", "93.38", "93.44" (93 values omitted).
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{f60sodum}{%
\subsection{F60SODUM}\label{f60sodum}}

\emph{Dietary Sodium (mg)}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2639}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 136 (0.16 \%) \\
Number of unique values & 83262 \\
Median & 2523.43 \\
1st and 3rd quartiles & 1896.51; 3278.58 \\
Min. and max. & 15.06; 36443.54 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-15-F60SODUM-1.pdf}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected:
  "15.06", "26.08", "69.75", "83.12", "160.6", \ldots, "22460.73",
  "24560.67", "25682.45", "27307.56", "36443.54" (1437 values omitted).
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{pulse30}{%
\subsection{PULSE30}\label{pulse30}}

\emph{Resting pulse in 30 seconds}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2083}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 142 (0.17 \%) \\
Number of unique values & 74 \\
Median & 34 \\
1st and 3rd quartiles & 31; 37 \\
Min. and max. & 20; 135 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-16-PULSE30-1.pdf}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected: "20",
  "21", "47", "48", "49", \ldots, "114", "128", "129", "133", "135" (39
  values omitted).
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{waist}{%
\subsection{WAIST}\label{waist}}

\emph{Waist, cm}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2083}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 302 (0.36 \%) \\
Number of unique values & 787 \\
Median & 81 \\
1st and 3rd quartiles & 74; 90 \\
Min. and max. & 35; 199 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-17-WAIST-1.pdf}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected: "35",
  "35.5", "36", "36.5", "37", \ldots, "191.8", "192", "195", "196",
  "199" (156 values omitted).
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{syst}{%
\subsection{SYST}\label{syst}}

\emph{Systolic BP}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1944}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 79 (0.09 \%) \\
Number of unique values & 114 \\
Median & 119 \\
1st and 3rd quartiles & 110; 127 \\
Min. and max. & 80; 139.5 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-18-SYST-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{dias}{%
\subsection{DIAS}\label{dias}}

\emph{Diastolic BP}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1944}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 91 (0.11 \%) \\
Number of unique values & 90 \\
Median & 72 \\
1st and 3rd quartiles & 68; 78 \\
Min. and max. & 40; 89.5 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-19-DIAS-1.pdf}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected: "40",
  "42", "42.5", "43", "44", \ldots, "55.5", "56", "56.5", "57", "57.5"
  (16 values omitted).
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{bmi}{%
\subsection{BMI}\label{bmi}}

\emph{Body-mass Index (BMI), kg/m2}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2083}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 726 (0.87 \%) \\
Number of unique values & 50372 \\
Median & 25.71 \\
1st and 3rd quartiles & 23.02; 29.27 \\
Min. and max. & 11.53; 69.88 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-20-BMI-1.pdf}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected:
  "11.53", "11.86", "11.97", "12.01", "12.11", \ldots, "69.33", "69.4",
  "69.55", "69.59", "69.88" (1248 values omitted).
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{walk}{%
\subsection{WALK}\label{walk}}

\emph{Times walk for \textgreater{} 10 min}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1389}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 6 \\
Median & 3 \\
1st and 3rd quartiles & 1; 4 \\
Min. and max. & 0; 5 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-21-WALK-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{walkmin}{%
\subsection{WALKMIN}\label{walkmin}}

\emph{Duration of walks when \textgreater10 min}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2500}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 11682 (14.01 \%) \\
Number of unique values & 4 \\
Mode & ``2'' \\
Reference category & 1 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-22-WALKMIN-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{walkspd}{%
\subsection{WALKSPD}\label{walkspd}}

\emph{Walking speed when walking for \textgreater10 min}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2083}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 11677 (14 \%) \\
Number of unique values & 5 \\
Mode & ``3'' \\
Reference category & 2 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-23-WALKSPD-1.pdf}

\begin{itemize}
\tightlist
\item
  The following suspected missing value codes enter as regular values:
  "9".
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{hrdex}{%
\subsection{HRDEX}\label{hrdex}}

\emph{Times per week of very hard exercise}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2083}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 681 (0.82 \%) \\
Number of unique values & 6 \\
Median & 0 \\
1st and 3rd quartiles & 0; 1 \\
Min. and max. & 0; 5 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-24-HRDEX-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{hrdexmin}{%
\subsection{HRDEXMIN}\label{hrdexmin}}

\emph{Duration per time of very hard exercise}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2500}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 60246 (72.23 \%) \\
Number of unique values & 4 \\
Mode & ``2'' \\
Reference category & 1 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-25-HRDEXMIN-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{modex}{%
\subsection{MODEX}\label{modex}}

\emph{Times per week of moderate exercise}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2083}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 688 (0.82 \%) \\
Number of unique values & 6 \\
Median & 0 \\
1st and 3rd quartiles & 0; 2 \\
Min. and max. & 0; 5 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-26-MODEX-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{modexmin}{%
\subsection{MODEXMIN}\label{modexmin}}

\emph{Duration per time of moderate exercise}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2500}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 44009 (52.76 \%) \\
Number of unique values & 4 \\
Mode & ``2'' \\
Reference category & 1 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-27-MODEXMIN-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{mldex}{%
\subsection{MLDEX}\label{mldex}}

\emph{Times per week of mild exercise}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2222}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 1413 (1.69 \%) \\
Number of unique values & 6 \\
Median & 0 \\
1st and 3rd quartiles & 0; 1 \\
Min. and max. & 0; 5 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-28-MLDEX-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{mldexmin}{%
\subsection{MLDEXMIN}\label{mldexmin}}

\emph{Duration per time of mild exercise}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2361}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 60472 (72.5 \%) \\
Number of unique values & 4 \\
Mode & ``4'' \\
Reference category & 1 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-29-MLDEXMIN-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{hrdex18}{%
\subsection{HRDEX18}\label{hrdex18}}

\emph{Very hard exercise 3 times/wk at age 18}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2222}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 2564 (3.07 \%) \\
Number of unique values & 2 \\
Mode & ``0'' \\
Reference category & 0 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-30-HRDEX18-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{hrdex35}{%
\subsection{HRDEX35}\label{hrdex35}}

\emph{Very hard exercise 3 times/wk at age 35}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2222}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 2270 (2.72 \%) \\
Number of unique values & 2 \\
Mode & ``0'' \\
Reference category & 0 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-31-HRDEX35-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{hrdex50}{%
\subsection{HRDEX50}\label{hrdex50}}

\emph{Very hard exercise 3 times/wk at age 50}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2222}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 1706 (2.05 \%) \\
Number of unique values & 2 \\
Mode & ``0'' \\
Reference category & 0 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-32-HRDEX50-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{tepiwk}{%
\subsection{TEPIWK}\label{tepiwk}}

\emph{Episodes recreational phys activity per week}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1389}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 43 \\
Median & 5 \\
1st and 3rd quartiles & 2.5; 8 \\
Min. and max. & 0; 25 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-33-TEPIWK-1.pdf}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected: "16.5",
  "17", "17.5", "18", "18.5", \ldots, "20.5", "21", "22", "23", "25" (2
  values omitted).
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{lepitot}{%
\subsection{LEPITOT}\label{lepitot}}

\emph{Episodes recreational phys activity per week \textgreater= 20 Min}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1389}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 43 \\
Median & 3.5 \\
1st and 3rd quartiles & 1; 6.5 \\
Min. and max. & 0; 25 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-34-LEPITOT-1.pdf}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected: "21",
  "22", "23", "25".
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{msepiwk}{%
\subsection{MSEPIWK}\label{msepiwk}}

\emph{Episodes moderate to strenuous phys activity per week}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1389}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 31 \\
Median & 2 \\
1st and 3rd quartiles & 0; 5 \\
Min. and max. & 0; 19 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-35-MSEPIWK-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{xlmsepi}{%
\subsection{XLMSEPI}\label{xlmsepi}}

\emph{Episodes moderate to strenuous activity \textgreater= 20 min/week}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1389}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 31 \\
Median & 1 \\
1st and 3rd quartiles & 0; 4.5 \\
Min. and max. & 0; 19 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-36-XLMSEPI-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{lmsepi}{%
\subsection{LMSEPI}\label{lmsepi}}

\emph{Episodes moderate to strenuous activity \textgreater=20 min/week
(categorical)}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1389}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 4 \\
Mode & ``2'' \\
Reference category & 1 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-37-LMSEPI-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{sepiwk}{%
\subsection{SEPIWK}\label{sepiwk}}

\emph{Strenuous activity episodes per week}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1389}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 6 \\
Median & 0 \\
1st and 3rd quartiles & 0; 1 \\
Min. and max. & 0; 6 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-38-SEPIWK-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{tminwk}{%
\subsection{TMINWK}\label{tminwk}}

\emph{Minutes of recreational phys activity per week}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1389}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 330 \\
Median & 150 \\
1st and 3rd quartiles & 60; 285 \\
Min. and max. & 0; 1750 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-39-TMINWK-1.pdf}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected: "960",
  "965", "967.5", "970", "980", \ldots, "1510", "1540", "1610", "1630",
  "1750" (56 values omitted).
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{msminwk}{%
\subsection{MSMINWK}\label{msminwk}}

\emph{Minutes of moderate to strenuous activity per week}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1389}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 235 \\
Median & 60 \\
1st and 3rd quartiles & 0; 180 \\
Min. and max. & 0; 1330 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-40-MSMINWK-1.pdf}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected: "1190",
  "1210", "1330".
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{sminwk}{%
\subsection{SMINWK}\label{sminwk}}

\emph{Minutes of strenuous phys activity per week}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1389}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 19 \\
Median & 0 \\
1st and 3rd quartiles & 0; 30 \\
Min. and max. & 0; 420 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-41-SMINWK-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{texpwk}{%
\subsection{TEXPWK}\label{texpwk}}

\emph{Total energy expend from recreational phys activity
(MET-hours/week)}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1667}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 1341 \\
Median & 10 \\
1st and 3rd quartiles & 3.5; 20 \\
Min. and max. & 0; 142.33 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-42-TEXPWK-1.pdf}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected: "74",
  "74.08", "74.17", "74.25", "74.33", \ldots, "130.33", "130.67",
  "134.17", "136.33", "142.33" (192 values omitted).
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{walkexp}{%
\subsection{WALKEXP}\label{walkexp}}

\emph{MET-hours per week from walking}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1528}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 41 \\
Median & 3.75 \\
1st and 3rd quartiles & 0; 7.5 \\
Min. and max. & 0; 40.83 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-43-WALKEXP-1.pdf}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected:
  "32.67", "40.83".
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{smoking}{%
\subsection{SMOKING}\label{smoking}}

\emph{Smoking status}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2083}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 773 (0.93 \%) \\
Number of unique values & 3 \\
Mode & ``0'' \\
Reference category & 0 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-44-SMOKING-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{hardexp}{%
\subsection{HARDEXP}\label{hardexp}}

\emph{Energy expenditure from hard exercise (MET-hours/week)}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1389}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 19 \\
Median & 0 \\
1st and 3rd quartiles & 0; 3.5 \\
Min. and max. & 0; 49 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-45-HARDEXP-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{modexp}{%
\subsection{MODEXP}\label{modexp}}

\emph{Energy expend from moderate exercise (MET-hours/week)}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1389}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 19 \\
Median & 0 \\
1st and 3rd quartiles & 0; 4.5 \\
Min. and max. & 0; 31.5 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-46-MODEXP-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{mildexp}{%
\subsection{MILDEXP}\label{mildexp}}

\emph{Energy expenditure from mild exercise (MET-hours/week)}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1389}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 19 \\
Median & 0 \\
1st and 3rd quartiles & 0; 1.5 \\
Min. and max. & 0; 21 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-47-MILDEXP-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{alcohol}{%
\subsection{ALCOHOL}\label{alcohol}}

\emph{Alcohol intake}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2083}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 389 (0.47 \%) \\
Number of unique values & 6 \\
Median & 4 \\
1st and 3rd quartiles & 3; 5 \\
Min. and max. & 1; 6 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-48-ALCOHOL-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{packyrs}{%
\subsection{PACKYRS}\label{packyrs}}

\emph{Pack years of smoking}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2222}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 2653 (3.18 \%) \\
Number of unique values & 202 \\
Median & 0 \\
1st and 3rd quartiles & 0; 12.5 \\
Min. and max. & 0; 158.75 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-49-PACKYRS-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{indrchor}{%
\subsection{INDRCHOR}\label{indrchor}}

\emph{Hours doing heavy chores}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2500}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 33093 (39.68 \%) \\
Number of unique values & 5 \\
Mode & ``2'' \\
Reference category & 1 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-50-INDRCHOR-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{yrdworkm}{%
\subsection{YRDWORKM}\label{yrdworkm}}

\emph{Months doing yard work}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2500}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 33219 (39.83 \%) \\
Number of unique values & 5 \\
Mode & ``1'' \\
Reference category & 1 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-51-YRDWORKM-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{yrdwrkh}{%
\subsection{YRDWRKH}\label{yrdwrkh}}

\emph{Hours in week doing yard work}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2500}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 52673 (63.15 \%) \\
Number of unique values & 5 \\
Mode & ``2'' \\
Reference category & 1 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-52-YRDWRKH-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{sitting}{%
\subsection{SITTING}\label{sitting}}

\emph{Number of hours spent sitting}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2500}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 33193 (39.79 \%) \\
Number of unique values & 8 \\
Median & 3 \\
1st and 3rd quartiles & 2; 5 \\
Min. and max. & 1; 8 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-53-SITTING-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{sleeping}{%
\subsection{SLEEPING}\label{sleeping}}

\emph{Number of hours spent sleeping}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2500}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 33103 (39.69 \%) \\
Number of unique values & 8 \\
Median & 4 \\
1st and 3rd quartiles & 3; 4 \\
Min. and max. & 1; 8 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-54-SLEEPING-1.pdf}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected: "5",
  "6", "7", "8".
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{yrdminwk}{%
\subsection{YRDMINWK}\label{yrdminwk}}

\emph{Min/wk of yard work}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2083}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 33367 (40 \%) \\
Number of unique values & 14 \\
Median & 20 \\
1st and 3rd quartiles & 0; 80 \\
Min. and max. & 0; 660 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-55-YRDMINWK-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{yardexp}{%
\subsection{YARDEXP}\label{yardexp}}

\emph{Energy expend from yard work}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2083}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 33367 (40 \%) \\
Number of unique values & 14 \\
Median & 1.33 \\
1st and 3rd quartiles & 0; 5.33 \\
Min. and max. & 0; 44 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-56-YARDEXP-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{inheaexp}{%
\subsection{INHEAEXP}\label{inheaexp}}

\emph{Energy expend heavy indoor chores}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2500}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 33093 (39.68 \%) \\
Number of unique values & 5 \\
Mode & ``7'' \\
Reference category & 0 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-57-INHEAEXP-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{inact}{%
\subsection{INACT}\label{inact}}

\emph{Hrs/day spent sitting or lying}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2500}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 33264 (39.88 \%) \\
Number of unique values & 17 \\
Median & 15 \\
1st and 3rd quartiles & 13; 17 \\
Min. and max. & 4; 24 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-58-INACT-1.pdf}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected: "4",
  "6.5", "24".
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{totestat}{%
\subsection{TOTESTAT}\label{totestat}}

\emph{Unopposed estrogen usage status}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1944}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 49 (0.06 \%) \\
Number of unique values & 3 \\
Mode & ``0'' \\
Reference category & 0 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-59-TOTESTAT-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{totpstat}{%
\subsection{TOTPSTAT}\label{totpstat}}

\emph{Estrogen + progesterone usage status}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1944}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 34 (0.04 \%) \\
Number of unique values & 3 \\
Mode & ``0'' \\
Reference category & 0 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-60-TOTPSTAT-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{tothstat}{%
\subsection{TOTHSTAT}\label{tothstat}}

\emph{HRT usage status}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1944}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 72 (0.09 \%) \\
Number of unique values & 3 \\
Mode & ``2'' \\
Reference category & 0 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-61-TOTHSTAT-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{nightswt}{%
\subsection{NIGHTSWT}\label{nightswt}}

\emph{Night sweats}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2083}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 399 (0.48 \%) \\
Number of unique values & 4 \\
Mode & ``0'' \\
Reference category & 0 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-62-NIGHTSWT-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{hotflash}{%
\subsection{HOTFLASH}\label{hotflash}}

\emph{Hot flashes}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2083}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 257 (0.31 \%) \\
Number of unique values & 4 \\
Mode & ``0'' \\
Reference category & 0 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-63-HOTFLASH-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{actdly}{%
\subsection{ACTDLY}\label{actdly}}

\emph{Activities of Daily Living Construct}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2222}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 2707 (3.25 \%) \\
Number of unique values & 8 \\
Median & 4 \\
1st and 3rd quartiles & 4; 4 \\
Min. and max. & 4; 12 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-64-ACTDLY-1.pdf}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected: "5",
  "6", "7", "8", "9", "10", "12".
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{physfun}{%
\subsection{PHYSFUN}\label{physfun}}

\emph{Physical Functioning Construct}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1944}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 671 (0.8 \%) \\
Number of unique values & 19 \\
Median & 90 \\
1st and 3rd quartiles & 80; 95 \\
Min. and max. & 10; 100 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-65-PHYSFUN-1.pdf}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected: "10",
  "15", "20", "25", "30", "35".
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{pshtdep}{%
\subsection{PSHTDEP}\label{pshtdep}}

\emph{Shortened CES-D/DIS Screening Instrument}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2222}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 1573 (1.89 \%) \\
Number of unique values & 2651 \\
Median & 0 \\
1st and 3rd quartiles & 0; 0.01 \\
Min. and max. & 0; 0.96 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-66-PSHTDEP-1.pdf}

\begin{itemize}
\tightlist
\item
  Note that the following possible outlier values were detected: "0",
  "0", "0", "0", "0", \ldots, "0.93", "0.94", "0.95", "0.95", "0.96"
  (1277 values omitted).
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{socfunc}{%
\subsection{SOCFUNC}\label{socfunc}}

\emph{Social Functioning}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2083}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 235 (0.28 \%) \\
Number of unique values & 9 \\
Median & 100 \\
1st and 3rd quartiles & 87.5; 100 \\
Min. and max. & 0; 100 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-67-SOCFUNC-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{htnrx}{%
\subsection{HTNrx}\label{htnrx}}

\emph{Anti-hypertensives}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1389}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 1 (0 \%) \\
Number of unique values & 2 \\
Mode & ``0'' \\
Reference category & 0 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-68-HTNrx-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{f33pillshyp}{%
\subsection{F33PILLSHYP}\label{f33pillshyp}}

\emph{F33 Pills For Hypertension}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1389}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 2 \\
Mode & ``0'' \\
Reference category & 0 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-69-F33PILLSHYP-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{timedy}{%
\subsection{timedy}\label{timedy}}

\emph{Days to HTN or censor}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1806}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 6547 \\
Median & 3649 \\
1st and 3rd quartiles & 2266; 5925 \\
Min. and max. & 123; 7295 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-70-timedy-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{timeyr}{%
\subsection{timeyr}\label{timeyr}}

\emph{Years to HTN or censor}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1944}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 6547 \\
Median & 9.99 \\
1st and 3rd quartiles & 6.2; 16.22 \\
Min. and max. & 0.34; 19.97 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-71-timeyr-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{educcat}{%
\subsection{educcat}\label{educcat}}

\emph{Education categories}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.2083}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 615 (0.74 \%) \\
Number of unique values & 3 \\
Mode & ``1'' \\
Reference category & 0 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-72-educcat-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{hxchd}{%
\subsection{HxCHD}\label{hxchd}}

\emph{Hx CHD (MI or Revasc)}

\begin{itemize}
\tightlist
\item
  The variable only takes one (non-missing) value: "0". The variable
  contains 0 \% missing observations.
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{prevcanc}{%
\subsection{prevCanc}\label{prevcanc}}

\emph{Hx Cancer}

\begin{itemize}
\tightlist
\item
  Note that this variable is treated as a factor variable below, as it
  only takes a few unique values.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.3611}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1389}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Feature
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Variable type & numeric \\
Number of missing obs. & 0 (0 \%) \\
Number of unique values & 2 \\
Mode & ``0'' \\
Reference category & 0 \\
\end{longtable}

\includegraphics{dataMaid_WHI.TotalPA.an_samp_files/figure-latex/Var-74-prevCanc-1.pdf}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{stroke_f2}{%
\subsection{stroke\_f2}\label{stroke_f2}}

\emph{Stroke ever}

\begin{itemize}
\tightlist
\item
  The variable only takes one (non-missing) value: "0". The variable
  contains 0 \% missing observations.
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

Report generation information:

\begin{itemize}
\item
  Created by: Connor (username: \texttt{Connor}).
\item
  Report creation time: Tue Nov 14 2023 14:55:19
\item
  Report was run from directory:
  \texttt{/Users/Connor/Library/CloudStorage/OneDrive-Personal/Desktop/WHI\ Total\ PA\ \&\ HTN\ R/whi-totalPA-htn}
\item
  dataMaid v1.4.1 {[}Pkg: 2021-10-08 from CRAN (R 4.2.0){]}
\item
  R version 4.2.0 (2022-04-22).
\item
  Platform: x86\_64-apple-darwin17.0 (64-bit)(macOS Monterey 12.4).
\item
  Function call:
  \texttt{makeDataReport(data\ =\ WHI.TotalPA.an\_samp,\ output\ =\ "html",\ replace\ =\ TRUE)}
\end{itemize}

\end{document}
